import { db, error, json, requireAuth, router } from '@appdeploy/sdk';
type Role='learner'|'educator';
type Profile={role:Role;educatorType?:'individual'|'organization';organizationType?:string;interests:string[];studyField:string;educationLevel:string;voiceBio:string;name?:string;email?:string;ownerUserId:string;createdAt:string;updatedAt:string};
const catalog=[{id:'v1',title:'How artificial intelligence actually learns',creator:'Mira Lab',category:'Artificial Intelligence',room:'AI Foundations',duration:'18:24',podcast:true},{id:'v2',title:'The hidden engineering of modern cities',creator:'Urban Systems',category:'Engineering',room:'Cities as Machines',duration:'27:10',podcast:true},{id:'v3',title:'What quantum physics says about reality',creator:'Dr. Lena Moss',category:'Physics',room:'Reality Lab',duration:'21:42',podcast:true},{id:'v4',title:'Design thinking beyond sticky notes',creator:'Forma Academy',category:'Design',room:'Designing Better Systems',duration:'14:09',podcast:true},{id:'v5',title:'The psychology of deep attention',creator:'Mind Atlas',category:'Psychology',room:'Human Mind',duration:'33:05',podcast:true},{id:'v6',title:'Why markets behave like living systems',creator:'Open Economics',category:'Economics',room:'Economics Without Jargon',duration:'24:18',podcast:true},{id:'v7',title:'Spaceflight: from equations to orbit',creator:'Orbital Classroom',category:'Space',room:'Space Systems',duration:'31:12',podcast:true},{id:'v8',title:'Architecture as a language of society',creator:'Studio North',category:'Architecture',room:'Reading Architecture',duration:'19:48',podcast:true}];
function table(userId:string){return `profile:${userId}`}
async function getProfile(userId:string){const {items}=await db.list<Profile>(table(userId),{limit:1});return items[0]||null}
function cleanText(value:unknown,max:number){return String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}

export const handler = router({
    "GET /api/_healthcheck": [async () => json({ message: "Success" })],
    'GET /api/profile':[requireAuth(),async ctx=>json({profile:await getProfile(ctx.user!.userId)})],
    'POST /api/profile':[requireAuth(),async ctx=>{const b=ctx.body as Partial<Profile>;if(b.role!=='learner'&&b.role!=='educator')return error('Invalid role',400);if(!Array.isArray(b.interests)||b.interests.length<1||b.interests.length>30)return error('Choose between 1 and 30 interests',400);const interests=b.interests.map(x=>cleanText(x,64)).filter(Boolean);const studyField=cleanText(b.studyField,120);const voiceBio=cleanText(b.voiceBio,2000);if(!interests.length)return error('At least one interest is required',400);if(!studyField)return error('Study field is required',400);if(!voiceBio)return error('Biography is required',400);if(b.role==='educator'&&b.educatorType!=='individual'&&b.educatorType!=='organization')return error('Educator type is required',400);const now=new Date().toISOString();const current=await getProfile(ctx.user!.userId);const record:Profile={role:b.role,educatorType:b.role==='educator'?b.educatorType:undefined,organizationType:b.role==='educator'&&b.educatorType==='organization'?cleanText(b.organizationType,80):undefined,interests,studyField,educationLevel:cleanText(b.educationLevel,80),voiceBio,name:ctx.user!.name,email:ctx.user!.email,ownerUserId:ctx.user!.userId,createdAt:current?.createdAt||now,updatedAt:now};if(current){const [ok]=await db.update(table(ctx.user!.userId),[{id:current.id,record:{...record}}]);if(!ok)return error('Profile update failed',500)}else{const [id]=await db.add(table(ctx.user!.userId),[{...record}]);if(!id)return error('Profile creation failed',500)}return json({profile:record})}],
    'GET /api/explore':[requireAuth(),async ctx=>{const p=await getProfile(ctx.user!.userId);if(!p)return error('Complete onboarding first',409);const signals=[...p.interests,p.studyField,p.voiceBio].join(' ').toLowerCase();const ranked=catalog.map((x,i)=>{let score=10-i;for(const interest of p.interests){if(x.category.toLowerCase().includes(interest.toLowerCase())||signals.includes(x.category.toLowerCase()))score+=25}const words=x.category.toLowerCase().split(/\\s+/);score+=words.filter(w=>w.length>3&&signals.includes(w)).length*5;return {...x,score}}).sort((a,b)=>b.score-a.score);return json({items:ranked})}],

})