import { useState } from 'react';
import { BookOpen, BriefcaseBusiness, Building2, ChevronLeft, ChevronRight, FileText, GraduationCap, Headphones, Layers3, PenLine, Play, Sparkles, UserRound, UsersRound, Video, Volume2 } from 'lucide-react';
import './tour.css';

const steps=['Intro','Identity','Explore','Rooms','Profiles','Next build'];
export default function ReviewTour(){const [step,setStep]=useState(0);function exit(){window.location.hash='';window.location.reload();}return <main className='review-tour'><header className='tour-header'><div className='tour-brand'><img src='./resources/logo.png' alt='Universal School'/><div><b>UNIVERSAL SCHOOL</b><span>UI REVIEW TOUR</span></div></div><button onClick={exit}>Exit tour</button></header><section className='tour-shell'><div className='tour-progress'>{steps.map((x,i)=><button key={x} className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)}><i>{i+1}</i><span>{x}</span></button>)}</div><div className='tour-canvas'>{step===0?<IntroStep/>:step===1?<IdentityStep/>:step===2?<ExploreStep/>:step===3?<RoomsStep/>:step===4?<ProfilesStep/>:<NextStep/>}</div><footer className='tour-footer'><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}><ChevronLeft/>Back</button><span>{step+1} / {steps.length}</span>{step<steps.length-1?<button className='tour-next' onClick={()=>setStep(s=>Math.min(steps.length-1,s+1))}>Next<ChevronRight/></button>:<button className='tour-next' onClick={exit}>Open app<ChevronRight/></button>}</footer></section></main>}
function IntroStep(){return <div className='tour-intro'><div className='tour-logo-orbit reference'><span/><img src='./resources/logo.png' alt='Universal School'/></div><p>NEXT-GENERATION EDUCATION SYSTEM</p><h1>Universal School</h1><div className='tour-reference-divider'><i/><b/><i/></div><small>Learn and Teach Without Limits</small><p className='tour-note'>This tour is a safe visual review. It does not change your saved account or profile.</p></div>}
function IdentityStep(){return <div className='tour-section'><p className='tour-kicker'>ONE ACCOUNT · MULTIPLE IDENTITIES</p><h2>Start as you are. Expand later.</h2><div className='tour-card-grid three'><TourCard icon={<GraduationCap/>} title='Learner' text='Learn, build Schools and follow RAVIs.'/><TourCard icon={<Volume2/>} title='RAVI' text='Teach, publish, sell courses and build an audience.'/><TourCard icon={<Building2/>} title='Organization' text='Run an institution, Campus, faculty and access.'/></div><div className='tour-interest-preview'><span>Academic Sciences</span><span>Life & Applied Skills</span></div></div>}
function ExploreStep(){return <div className='tour-section'><p className='tour-kicker'>DISCOVERY</p><h2>Explore stays simple.</h2><p className='tour-copy'>The core discovery experience will separate the three public content formats instead of mixing everything into one feed.</p><div className='tour-card-grid three'><TourCard icon={<Video/>} title='Video' text='Short and long-form educational video.'/><TourCard icon={<Headphones/>} title='Podcast' text='Podcasts and voice-first learning.'/><TourCard icon={<PenLine/>} title='Text' text='Ideas, questions, announcements and discussion.'/></div></div>}
function RoomsStep(){return <div className='tour-section'><p className='tour-kicker'>LEARNING ARCHITECTURE</p><h2>Four Rooms. Four purposes.</h2><div className='tour-card-grid four'><TourCard icon={<Building2/>} title='Campus' text='Institution-led learning.'/><TourCard icon={<UsersRound/>} title='Academy' text='RAVI collective.'/><TourCard icon={<Layers3/>} title='School' text='Learner-built education.'/><TourCard icon={<BriefcaseBusiness/>} title='Workshop' text='Collaborative project space.'/></div></div>}
function ProfilesStep(){return <div className='tour-section'><p className='tour-kicker'>SOCIAL LEARNING PROFILES</p><h2>Profiles become the public identity layer.</h2><div className='tour-profile-preview'><div className='tour-avatar'><UserRound/></div><div><small>RAVI</small><b>Dr. Razavi</b><p>AI & engineering RAVI · courses · community · resources</p></div></div><div className='tour-tab-preview'><span><Video/>Videos</span><span><Headphones/>Podcast</span><span><PenLine/>Text</span><span><GraduationCap/>Courses</span><span><FileText/>PDFs</span><span><BookOpen/>Books</span></div></div>}
function NextStep(){return <div className='tour-section'><p className='tour-kicker'>CURRENT BUILD MAP</p><h2>The UI foundation is now preserved.</h2><div className='tour-build-list'><BuildRow n='01' title='Explore' text='Video · Podcast · Text discovery and interaction.'/><BuildRow n='02' title='Public profiles' text='Learner · RAVI · Organization real viewing flows.'/><BuildRow n='03' title='Player' text='Video learning player and AI learning tools.'/><BuildRow n='04' title='Settings' text='Identity, privacy, plans, access and account controls.'/><BuildRow n='05' title='MVP connections' text='Database, payments, media, AI APIs and production rules.'/></div><div className='tour-safe'><Sparkles/><span>Your normal app remains separate from this review tour.</span></div></div>}
function TourCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className='tour-card'><span>{icon}</span><b>{title}</b><p>{text}</p><ChevronRight/></article>}
function BuildRow({n,title,text}:{n:string;title:string;text:string}){return <div className='tour-build-row'><span>{n}</span><div><b>{title}</b><p>{text}</p></div></div>}
